### ISSUE TITLE
Not able to delete Businesses

### ISSUE THREAD

**Issue by rahulkpg** [kaoskeya/meteor-admin#10]
![image](https://cloud.githubusercontent.com/assets/1405287/6185485/d425693c-b394-11e4-8a51-eaa3c1f36f11.png)

I am able to delete users but businesses cannot be deleted still, even when they have no admin's anymore

**Comment by kaoskeya** [comment]
The delete was not happening because of the allow/deny rules on the collection. I've fixed it and tried a creation and deletion and it worked fine. Closing this. Please reopen if you think this issue isn't resolved.

**Developer future reference:**
The autoform forms follow the allow/deny rules of your app. 
If the form does not seem to work as expected, run `AutoForm.debug()` in the console to see error messages logged.
