### ISSUE TITLE
Unable to reset user password from Admin Panel 

### ISSUE THREAD

**Issue by rahulkpg** [kaoskeya/meteor-admin#13]
There is no option to reset(or set) user passwords from the Admin .

**Comment by kaoskeya** [comment]
This somehow slipped through. Critical functionality and will get this done in the next push. 
Something similar to the yogiben:meteor-admin is what I'll try for, it not custom edit templates which would solve a lot more problems and add more functionality.

**Comment by kaoskeya** [comment]
Support for custom create/read/update templates has been added. This functionality is up next.

**Comment by kaoskeya** [comment]
Alright, its been a while since I've pushed anything here. Some bad news, I got mugged a few days ago and had to let go of something I've treasured for long - my laptop :( Not a good feeling at all. Did a few things to try and get her back, but nope.

Really sorry about all the delay guys, I've gotten my hands on a temporary machine for now, once I set it all up and clear the back log, will churn out code to this repo. The time off work has let me think of a few more cool things for this project.

The 0.2.0 and 0.3.0 milestones I've pushed them back by 15 days each, will totally get them done.

Thanks for the app installs guys :)

**Comment by gam-ragnar** [comment]
Sorry about being mugged, I hope you okay, I mean besides the laptop?

**Comment by kaoskeya** [comment]
Hey, thanks for asking, yes I'm ok :)

**Comment by kaoskeya** [comment]
I really liked the `accounts-admin-ui-bootstrap-3`, but found that a PR has not been accepted for a while now.

Forked the PR repo and published it on atmosphere with a few dependency fixes and modified the meteor-admin to support CRUD (table view) templates apart from the previously supported separate Create, Read, Update and Delete templates.

You can use it by running `meteor add kaoskeya:accounts-admin-ui-bootstrap-3`

Your admin config will be something like:

`User: {
    tableColumns: [],
    templates: {
        "crud": { name: 'accountsAdmin' }
    }
}`

You can mange users, roles, user levels etc. Reset password is not there yet as per this issue, but will be done there, have opened [an issue](https://github.com/kaoskeya/meteor-accounts-admin-ui-bootstrap-3/issues/1) in that repo. 

Accounts specific stuff will be on that repo going forward and I will be rewriting parts of it.
